name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.9.2
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=3.2.0 <=4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: 1.0.0 
  signature: ^5.4.0
  rxdart: ^0.27.7
  json_annotation: ^4.8.0
  simple_html_css: ^5.0.0
  just_audio: ^0.9.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: any
  json_serializable: any
  test: any

flutter:
  assets:
    - assets/icons/analysis.png
    - assets/icons/archive.png
    - assets/icons/checkmark.png
    - assets/icons/deadline.png
    - assets/icons/document.png
    - assets/icons/handshake.png
    - assets/icons/health.png
    - assets/icons/id.png
    - assets/icons/location.png
    - assets/icons/management.png
    - assets/icons/networking.png
    - assets/icons/settings.png
    - assets/icons/target.png
    - assets/icons/task.png
    - assets/lang/
    - assets/audio/RPTimerStepSound.mp3
